### PR TITLE
Chores/fix map

### PR DESCRIPTION
**Pull request by armandfardeau**
### Existing positions
```
bundle exec rake decidim_homepage_interactive_map:repair_data
```

### New positions
No need to do anything, the module will automatically transpose the scope position.

See readme for installation instructions, especially:
* On OSX:
```bash
brew install proj
bundle config set build.rgeo-proj4 --with-proj-dir="/opt/homebrew/"
bundle pristine rgeo-proj4
bundle install
```

* On Ubuntu:
```bash
PROJ_VERSION=proj-9.1.1 ./.github/install_proj.sh
bundle config set build.rgeo-proj4 --with-proj-dir="/usr/local/bin/"
bundle pristine rgeo-proj4
bundle install
```

### CODE REVIEW

**Comment by paulinebessoles** [comment]
Thank you @armandfardeau! I have an issue when trying to geo-localize a scope. 
Capture d’écran 2023-01-17 à 18 42 55
```
NameError (uninitialized constant Decidim::HomepageInteractiveMap::CoordinatesSwapper):
  
decidim-module-homepage_interactive_map (7bd37ebf30ea) app/commands/decidim/admin/update_scope.rb:49:in `attributes'
decidim-module-homepage_interactive_map (7bd37ebf30ea) app/commands/decidim/admin/update_scope.rb:37:in `update_scope'
decidim-module-homepage_interactive_map (7bd37ebf30ea) app/commands/decidim/admin/update_scope.rb:25:in `call'
rectify (0.13.0) lib/rectify/command.rb:30:in `call'
decidim (e85c208edf36) decidim-admin/app/controllers/decidim/admin/scopes_controller.rb:47:in `update'
actionpack (6.0.5.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.5.1) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.5.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.5.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.5.1) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
activesupport (6.0.5.1) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
decidim (e85c208edf36) decidim-core/app/controllers/concerns/decidim/use_organization_time_zone.rb:21:in `use_organization_time_zone'
activesupport (6.0.5.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
decidim (e85c208edf36) decidim-core/app/controllers/concerns/decidim/locale_switcher.rb:24:in `switch_locale'
activesupport (6.0.5.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.5.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.5.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.5.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.5.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.5.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.5.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.5.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.5.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.5.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.5.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.5.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.5.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.5.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.5.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.5.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.5.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.5.1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.5.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.5.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.5.1) lib/rails/engine.rb:527:in `call'
railties (6.0.5.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.5.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.5.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.5.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.5.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.5.1) lib/rails/engine.rb:527:in `call'
railties (6.0.5.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.5.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.5.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.5.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.5.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.5.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
batch-loader (1.5.0) lib/batch_loader/middleware.rb:11:in `call'
omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.0) lib/omniauth/builder.rb:44:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
decidim (e85c208edf36) decidim-core/lib/decidim/middleware/strip_x_forwarded_host.rb:12:in `call'
decidim-decidim_awesome (0.8.3) app/middleware/decidim/decidim_awesome/current_config.rb:33:in `call'
decidim (e85c208edf36) decidim-core/lib/decidim/middleware/current_organization.rb:22:in `call'
rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
actionpack (6.0.5.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/cookies.rb:654:in `call'
activerecord (6.0.5.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.5.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.5.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.5.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.5.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.5.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.5.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.5.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.5.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
activesupport (6.0.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
webpacker (6.0.0.rc.5) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.7.2) lib/rack/proxy.rb:67:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
railties (6.0.5.1) lib/rails/engine.rb:527:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by armandfardeau** [comment]
Should be good now

**Comment by paulinebessoles** [comment]
I encounter another issue when creating a geolocalized scoped now.

To reproduce: 
1. Go to /admin/scopes route
2. Edit a scope
3. Enable geoloc
4. Add a valid GEOJSON code
5. Click on update 

` undefined method `_create' for RGeo::CoordSys::CRSToCRS:Class Did you mean? create `

```
rgeo-proj4 (3.1.1) lib/rgeo/coord_sys/crs_to_crs.rb:14:in `create'
rgeo-proj4 (3.1.1) lib/rgeo/coord_sys/crs_to_crs.rb:96:in `block in initialize'
rgeo-proj4 (3.1.1) lib/rgeo/coord_sys/crs_to_crs.rb:102:in `block in get'
rgeo-proj4 (3.1.1) lib/rgeo/coord_sys/crs_to_crs.rb:101:in `synchronize'
rgeo-proj4 (3.1.1) lib/rgeo/coord_sys/crs_to_crs.rb:101:in `get'
rgeo-proj4 (3.1.1) lib/rgeo/coord_sys/crs_to_crs.rb:89:in `get'
rgeo-proj4 (3.1.1) lib/rgeo/coord_sys/proj4.rb:225:in `transform_coords'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:48:in `transform_coords'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:42:in `block in transform'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:37:in `map'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:37:in `transform'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:39:in `block in transform'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:37:in `map'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:37:in `transform'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:39:in `block in transform'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:37:in `map'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:37:in `transform'
decidim-module-homepage_interactive_map (41e2f9ba68a2) lib/decidim/homepage_interactive_map/coordinates_swapper.rb:17:in `convert_geojson'
decidim-module-homepage_interactive_map (41e2f9ba68a2) app/commands/decidim/admin/update_scope.rb:51:in `attributes'
decidim-module-homepage_interactive_map (41e2f9ba68a2) app/commands/decidim/admin/update_scope.rb:39:in `update_scope'
decidim-module-homepage_interactive_map (41e2f9ba68a2) app/commands/decidim/admin/update_scope.rb:27:in `call'
rectify (0.13.0) lib/rectify/command.rb:30:in `call'
decidim (e85c208edf36) decidim-admin/app/controllers/decidim/admin/scopes_controller.rb:47:in `update'
actionpack (6.0.6.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.6.1) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.6.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
activesupport (6.0.6.1) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
decidim (e85c208edf36) decidim-core/app/controllers/concerns/decidim/use_organization_time_zone.rb:21:in `use_organization_time_zone'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
decidim (e85c208edf36) decidim-core/app/controllers/concerns/decidim/locale_switcher.rb:24:in `switch_locale'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.6.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.6.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.6.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.6.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.6.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.6.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
railties (6.0.6.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.6.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
railties (6.0.6.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.6.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
batch-loader (1.5.0) lib/batch_loader/middleware.rb:11:in `call'
omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.0) lib/omniauth/builder.rb:44:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
decidim (e85c208edf36) decidim-core/lib/decidim/middleware/strip_x_forwarded_host.rb:12:in `call'
decidim-decidim_awesome (0.8.3) app/middleware/decidim/decidim_awesome/current_config.rb:33:in `call'
decidim (e85c208edf36) decidim-core/lib/decidim/middleware/current_organization.rb:22:in `call'
rack (2.2.6.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.6.2) lib/rack/etag.rb:27:in `call'
rack (2.2.6.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.6.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.6.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.6.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.6.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/cookies.rb:654:in `call'
activerecord (6.0.6.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.6.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.6.2) lib/rack/method_override.rb:24:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
webpacker (6.0.0.rc.5) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.7.6) lib/rack/proxy.rb:87:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

**Comment by paulinebessoles** [comment]
Hi @armandfardeau, thank you for the instructions, I installer proj and was able to see that upcoming meetings pins are displayed too when the interactive map is enabled. 
We just have a problem with the geojson on the interactive map: the tile should be displayed on the map on a Toulouse neighbourhood but is instead displayed in Niger. Could you take a look?

**Review by paulinebessoles — APPROVED** [review]
It works well, thank you @armandfardeau! Both the localization and the pin's display on the upcoming meetings map

**Review by eliegaboriau — APPROVED** [review]
LGTM

**Pull request merged**
